Bulk broken link updates
MicrosoftDocs/biztalk-docs pull request #926
Opened 2023-10-12 16:24 UTC by mohitp930

This PR contains fixes to broken links - [User story 168849](https://github.com/Mi)crosoftDocs/biztalk-docs

2023-10-12 19:49 UTC, mohitp930 commented
@ecfan This pull request is ready for review. Couple notes for this. There does not seem to be a Microsoft hosted download link for the WCF LOB adapter SDK, but there is a bunch of documentation related to it, so I wonder if I've just missed it somewhere in my search. Also the SAP client links in software-prerequisites-for-biztalk-adapter-pack-2016.md might be hosted behind the SAP download center, but I don't have an account to verify.

2023-10-17 19:54 UTC, ecfan commented on biztalk/adapters-and-accelerators/adapter-sap/step-2-create-an-application-definition-file-for-the-sap-artifacts.md
> +-   Be sure that you have the Business Data Catalog Definition Editor installed as part of the Microsoft Office SharePoint Server 2007 SDK.
Consistency edit:

```suggestion
-   You must have the Business Data Catalog Definition Editor installed as part of the Microsoft Office SharePoint Server 2007 SDK.
```

2023-10-17 19:54 UTC, ecfan commented on biztalk/adapters-and-accelerators/adapter-oracle-ebs/step-2-create-an-application-definition-file-for-the-oracle-ebs-artifacts.md
> +-   Be sure that you have the Business Data Catalog Definition Editor installed as part of the Microsoft Office SharePoint Server 2007 SDK.
```suggestion
-   You must have the Business Data Catalog Definition Editor installed as part of the Microsoft Office SharePoint Server 2007 SDK.
```

2023-10-17 19:58 UTC, ecfan requested changes
Feedback suggestions, thanks!

2023-10-17 21:44 UTC, ecfan approved these changes
Thanks, @mohitp930!

2023-10-17 21:45 UTC, merged